config/routes.rb
MediOnRails::Application.routes.draw do
  get "users/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root                   to:'summer#index'
  match '/ava',          to:'summer#ava'
  match '/don',          to:'summer#donate'
  match '/fundraising',  to:'summer#fundraising'
  match '/gislin',       to:'summer#gislin'
  match '/index',        to:'summer#index'
  match '/introduction', to:'summer#introduction'
  match '/jeff',         to:'summer#jeff'
  match '/video',        to:'summer#video'

  match '/signup',       to:'users#new'
  match '/signin',       to: 'sessions#new'
  match '/signout',      to: 'sessions#destroy', via: :delete

  match '/static_pages_home', to:'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }

  default_scope order: 'microposts.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy

  before_save { |user| user.email = email.downcase }

  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user,  only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to static_pages_home_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to static_pages_home_path
  end

  private

    def correct_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to static_pages_home_path if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user

      #@ControllerText = 'from session controller'
      redirect_back_or user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/controllers/summer_controller.rb
class SummerController < ApplicationController
  def ava
  end

  def donate
  end

  def fundraising
  end

  def gislin
  end

  def index
  end

  def introduction
  end

  def jeff
  end

  def video
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update,:destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token         #really create a cookie from user.create_remember_token, and save it into browser
    self.current_user=(user)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def signed_in_user
    unless signed_in?
      store_location
      flash[:notice] = "Please sign in."
      redirect_to signin_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/summer_helper.rb
module SummerHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav pull-left">
        <li><%= link_to "Home Page", index_path %></li>
        <li><%= link_to "Video Interview", video_path %></li>
        <li><%= link_to "Study Introduction", introduction_path %></li>
        <li><%= link_to "Importance of Fundraising", fundraising_path %></li>
        <li><%= link_to "Danate Now", don_path %></li>
        <li onClick="turnColor('white')"><a href="#">White </a></li>
        <li onClick="turnColor('black')"><a href="#">Black </a></li>
      </ul>

      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Sign up", signup_path %></li>
          <% if signed_in? %>

              <li><%= link_to "Users", users_path %><%= link_to "Settings",edit_user_path(current_user) %></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %>  </li>
          <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
          <% end%>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediOnRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'layouts/header'%>
   <br/>
   <br/>
   <% flash.each do |key, value| %>
         <div class="alert alert-<%= key %>"><%= value %></div>
   <% end %>
   <div class="container">
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                  data: { confirm: "You sure?" },
                  title: micropost.content %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
      <%= link_to "delete", feed_item, method: :delete,
                  data: { confirm: "You sure?" },
                  title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/home.html.erb
<br/>
<br/>
<br/>
<% if signed_in? %>
    <div class="row">
      <aside class="span4">
        <section>
          <%= render 'shared/user_info' %>
        </section>
        <section>
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="span8">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>
    <div class="center hero-unit">
      <h1>Welcome to the Sample App</h1>

      <h2>
        This is the home page for the
        <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
      </h2>

      <%= link_to "Sign up now!", signup_path,
                  class: "btn btn-large btn-primary" %>
    </div>

    <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>

app/views/summer/ava.html.erb
<div id="editableBelt" style="height:auto"onLoad="changePageType('ava')">
  <div id="header" align="center">

    <img src="/avaHeader.jpg" width="100%"/>
  </div>
  <ul id="nav">
  </ul>

  <div id="spaceForSubmenue"></div>
  <div id="plaine">
    <p>
      Dr. Ava Katherine Bittner is a licensed
      Optometrist who received her Ph.D. in clinical investigation from the Johns
      Hopkins School of Public Health. She completed a clinical research postdoctoral
      fellowship at the Johns Hopkins Wilmer Eye Institute, and then
      joined the faculty as an Assistant Professor. Dr. Bittner is a recipient of the
      prestigious Ezell fellowship award from the American Academy of Optometry.
      She was also inducted into the Phi Beta Kappa national academic
      honor society for excellence in her Ph.D. thesis work, which examined the
      relationships between psychosocial factors (stress, anxiety, mood, depression)
      and day-to-day variations in vision among visually impaired patients with
      retinis pigmentosa.
      Dr. Bittner aims to extend this research to patients with glaucoma, and
      to design and conduct clinical trials involving interventions for these
      patients in the future. Her research interests also include complementary
      and alternative approaches to sight preservation and disease/symptom
      attenuation in patients with retinal degenerations, using techniques
      such as yoga, acupuncture or mindfulness-based stress reduction. Dr.
      Bittner collaborates with researchers from the Johns Hopkins Center
      for Mind-Body Research and Department of Behavioral Science on this
      multidisciplinary work.
    </p>
  </div>
</div>

app/views/summer/donate.html.erb
<div id="editableBelt" style="height:auto" onLoad="changePageType('donate')">
  <div id="header" align="center">
    <!-- <div class="headerTxt">Acupuncture for the Treatment of Vision Loss Due to Retinitis Pigmentosa
    </div>
    -->
    <img src="/redHeader.jpg" width="100%"/>
  </div>




  <ul id="nav">
  </ul>

  <!--
  <div class="clear"/>
  -->
  <div class="donateTitle" align="center">
    <!--<div align="center">-->

    <span><br/>Three ways to support Acupuncture for RP</span>
  </div>

  <div class="donateBox">
    <div class="donateBoxImgGrid">
      <div id="computer">
        <img src="/computer.jpg" />
      </div>
      <br/>
      <span>OnLine</span>
    </div>


    <div class="donateBoxGrid">
      <p>Please complete our <br/><a href="https://jhweb.dev.jhu.edu/eforms/form.do?formId=17183"> secure online giving form</a>.<br/> designate your gift to "Other" and <br/>list "Acupuncture for RP" as</p>
    </div>
    <div class="donateBoxGrid">
      <br/>
      <div id="donateDemo">
        <img src="/donateDemo.jpg" width="450" />
      </div>
    </div>
  </div>

  <div class="donateBox">
    <div class="donateBoxImgGrid">
      <div id="phone">
        <img src="/phone.jpg" />
      </div>
      <br/>
      <span>By Phone</span>
    </div>
    <div class="donateBoxGrid">
      <p> To speak to someone directly about making a gift, please call 410-955-2020.</p>
    </div>
    <div class="donateBoxGrid">
    </div>
  </div>

  <div class="donateBox">
    <div class="donateBoxImgGrid">
      <div id="mail">
        <img src="/mail.jpg" />
      </div>
      <br/>
      <span >By Mail</span>
    </div>
    <div class="donateBoxGrid" >
      <p> Please Mail your <br/> <a href="/Wilmer Charitable Giving Form.pdf"> giving form</a> to:</p>
    </div>
    <div class="donateBoxGrid">
      <p>
        The Wilmer Eye Institute
        <br/>Wilmer Development Office,
        <br/>Wilmer 112
        <br/>600 North Wolfe Street
        <br/>Baltimore, MD 21287-9015
      </p>
    </div>
  </div>



</div>

app/views/summer/fundraising.html.erb
<div id="editableBelt" style="height:auto" onLoad="changePageType('fundraising')">
  <div id="header" align="center">

    <img src="/redHeader.jpg" width="100%"/>
  </div>

  <ul id="nav">
  </ul>
  <div id="plaine">
    <p>Patients come to the Wilmer Eye Institute from all over the nation and the world to receive the finest ophthalmic care. What many may not realize is that world-class patient care is only one third of our mission. The other integral parts of Wilmer are innovative research and teaching the next generation. Without all three components, Wilmer would not be the model eye institute many consider it to be. Every day at Wilmer, a teacher&acute;s observation inspires a student&acute;s efforts in the laboratory. A scientist&acute;s discovery culminates in a promising new therapy. A physician struggling to help a patient with a seemingly untreatable condition experiences an insight that leads to new research. This is academic medicine at its best-a creative, synergistic juxtaposition of clinic and operating room, classroom and laboratory. Faculty members must raise enough funds, whether from grants or private philanthropy, to pay for their own salary and that of their staff, as well as costs of special equipment and supplies needed for research. It is therefore critical that we raise $100,000 per year from private donors and foundations to fund acupuncture research for RP that will substantiate our study and enable us to apply for government funding that will then take our research to the next level.
    </p>
  </div>

</div>

app/views/summer/gislin.html.erb
<div id="editableBelt" style="height:auto" onLoad="changePageType('gislin')">
  <div id="header" align="center">
    <img src="/gislinHeader.jpg" width="100%">
  </div>
  <ul id="nav">
  </ul>
  <div id="plaine">
    <p >
      Gislin Dagnelie, Ph.D., is an Associate Professor of Ophthalmology in
      the Johns Hopkins University School of Medicine and the associate director of the Lions Vision
      Research and Rehabilitation Center, a division of the Wilmer Eye Institute. His work over the
      last 20 years has been supported by grants from the National Eye Institute, National Center for
      Complementary and Alternative Medicine, National Science Foundation, Foundation Fighting
      Blindness, and several companies developing ophthalmic devices and/or visual prosthetics. In
      addition to his role as the Center Principal Investigator for the Optobionics (2004-2007)
      and Second Sight Argus 2 (2007-present) clinical trials, Dr. Dagnelie is leading an NEI-sponsored effort
      to convert standard personal computers into precise tools for visual function measurement
      through development of an affordable calibration device.
      Dr. Dagnelie is a native of the Netherlands, where he grew up in Rotterdam. He received a master&acute;s degree in experimental physics at the University
      of Groningen, and a Ph.D. in medical physics at the University of Amsterdam. In 1986, Dr.
      Dagnelie became a postdoctoral fellow in the department of ophthalmology at Johns Hopkins,
      and remains a member of the research staff at this center to this day.
    </p>

  </div>
</div>

app/views/summer/introduction.html.erb
<div id="editableBelt" style="height:auto">
  <div id="header" align="center">

    <img src="/redHeader.jpg" width="100%"/>
  </div>

  <ul id="nav">
  </ul>
  <div id="plaine">
    <p>In 2006-07, Drs. Bittner and Dagnelie conducted a survey of alternative therapies used by people with RP, and found that the majority of those who had tried acupuncture reported an effect on vision. However, there are currently no publications of rigorously conducted placebo controlled studies to test acupuncture for its potential to improve vision in RP. Recently, Drs. Bittner and Dagnelie were introduced to an acupuncturist and naturopathic physician, Dr. Andy Rosenfarb, by an RP patient from Maryland who felt that her vision was improved after receiving acupuncture from Dr. Rosenfarb.  Based on his experience treating nearly 200 RP patients, he developed a standard protocol involving 2-weeks of electroacupuncture that is currently being tested in 12 people with RP as part of a pilot study at Johns Hopkins University. We hope to advance management options for RP, which are currently limited to nutritional supplements attempting to slow disease progression. After being diagnosed with a disabling, chronic disease, such as RP, there is nothing more disheartening than for the patient to hear that nothing can be done to treat it. The goal of our research is to provide a basis for recommendations to RP patients regarding safety and potential for vision changes, by identifying the proportion of patients who respond to the treatment, types of vision improvements, as well as the duration and magnitude of the effects.
    </p>
  </div>

</div>

app/views/summer/jeff.html.erb
<div id="editableBelt" style="height:auto">
  <div id="header" align="center">
    <img src="/jeffHeader.jpg" width="100%">
  </div>

  <ul id="nav">
  </ul>

  <div id="plaine">
    <p >
      Mr. Gould is a graduate of the Oregon College of Oriental Medicine and has a Master of Education from the University of Maryland College Park in Counseling and Personnel Services. He is nationally board certified in both acupuncture and Chinese herbology. He served as clinic supervisor for Tai Sophia Institute&acute;s Chinese Herb Program, and was the consulting editor for Wanzhu Hou&acute;s Treating Autoimmune Disease with Chinese Medicine, 2011, published by Elsevier.  Mr. Gould provided acupuncture for the study &quot;A Multi-Center Randomized Controlled Double Blind Trial Assessing the Effect of Acupuncture in Reducing Musculoskeletal Symptoms in Breast Cancer Patients Taking Aromatase Inhibitors,&quot; which was conducted at Johns Hopkins. Mr. Gould is currently working on &quot;Acupuncture in the Treatment of Idiopathic Gastroparesis: A Random, Single-Blind Pilot Study,&quot; also at Johns Hopkins.
    </p>
  </div>
</div>

app/views/summer/video.html.erb
<div id="editableBelt" style="height:auto">
  <div id="header" align="center">

    <img src="/redHeader.jpg" width="100%"/>    </div>
  <ul id="nav">
  </ul>
  <div id="plaine" align="center">
    <br/>
    <object id="MediaPlayer" width=900 height=630 classid="CLSID:22D6f312-B0F6-11D0-94AB-0080C74C7E95" standby="Loading Windows Media Player components..." type="application/x-oleobject" codebase="http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=6,4,7,1112">
      <param name="filename" value="/RP-Acupuncture12806.wmv">
      <param name="Showcontrols" value="True">
      <param name="autoStart" value="True">
      <param name="wmode" value="transparent">

      <embed type="application/x-mplayer2" src="/RP-Acupuncture12806.wmv" name="MediaPlayer" autoStart="True" wmode="transparent" width="900" height="630" ></embed>

    </object>

  </div>


</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<br/>
<br/>
<br/>

<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<br/>
<br/>
<br/>
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'shared/error_messages' %>
    <%= form_for(@user) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb

<br/>
<br/>
<br/>



<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>

  <div class="span8">
    <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>
